### ISSUE TITLE
Chức năng Quản lý tài khoản

### ISSUE THREAD

**Issue by trahongquan** [trahongquan/BT-TT_Team-77CH-QLTTBCNTT#17]
Tạo Chức năng Quản lý tài khoản:
SQL: QueryTK
FormAccMgr()
FormAccMgr_Load(object, EventArgs): void
ScrClr(): void
Display(): void
fixString(string): string
getAcc(): Account
thêm ToolStripMenultem_Click(object, EventArgs): void
sửa ToolStripMenultem_Click(object, EventArgs): void
xoá ToolStripMenultem_Click(object, EventArgs): void
txtTK_TextChanged(object, EventArgs): void
dtgvAcc_MouseClick_1(object, MouseEventArgs): void
listDelAccToolStripMenultem_Click(object, EventArgs): void
listAccActive ToolStripMenultem_Click(object, EventArgs): void
cbbQN_TextChanged(object, EventArgs): void

**Comment by Theanh09061993** [comment]
done chức năng quản lý tài khoản

**Comment by trahongquan** [comment]
oke

**Comment by trahongquan** [comment]
Done conflict và chức năng quản lý tài khoản
