### ISSUE TITLE
Chức năng quản lý Danh mục đơn vị

### ISSUE THREAD

**Issue by trahongquan** [trahongquan/BT-TT_Team-77CH-QLTTBCNTT#19]
QueryDV: QueryDonvi
FormDVO
FormDV_Load(object, EventArgs): void
AddDV_Click(object, EventArgs): void
ModifyDV_Click(object, EventArgs): void
DeITDV_Click(object, EventArgs): void
GetDVO: Donvi
Input(): bool
Clear(): void
Reload(): void
Display(): void
dtgvDV_MouseClick(object, MouseEventArgs) : void

**Comment by phamquangduan** [comment]
Da nhan

**Comment by trahongquan** [comment]
Cập nhật sửa lỗi
