### ISSUE TITLE
Tài liệu "Báo cáo nghiên cứu tính khả thi"

### ISSUE THREAD

**Issue by trahongquan** [trahongquan/BT-TT_Team-77CH-QLTTBCNTT#3]
Anh Thế Anh tạo và hoàn thiện Tài liệu "Báo cáo nghiên cứu tính khả thi.doc"
Hạn hoàn thành trước ngày 17/11

**Comment by Theanh09061993** [comment]
Đã hoàn thành tài liệu BC Tính khả Thi theo yêu cầu

**Comment by trahongquan** [comment]
Oke
