### ISSUE TITLE
Tài liệu "Kế hoạch dự án"

### ISSUE THREAD

**Issue by trahongquan** [trahongquan/BT-TT_Team-77CH-QLTTBCNTT#4]
Trên cơ sở Tài liệu "Báo cáo nghiên cứu tính khả thi" viết Tài liệu "Kế hoạch dự án"
Hạn hoàn thành trước ngày 18/11.

**Comment by Theanh09061993** [comment]
Đã nhận!

**Comment by trahongquan** [comment]
Done Issue
