### ISSUE TITLE
Tài liệu đặc tả yêu cầu

### ISSUE THREAD

**Issue by trahongquan** [trahongquan/BT-TT_Team-77CH-QLTTBCNTT#5]
Đ/c Duẩn:
Trên cơ sở KH thực hiện dữ án, tiến hành nghiên cứu và viết tài liệu đặc tả yêu cầu
Hạn hoàn thiện trước ngày 19/11

**Comment by phamquangduan** [comment]
Đã nhận!

**Comment by trahongquan** [comment]
gửi lại bản sửa

**Comment by trahongquan** [comment]
Done
