### ISSUE TITLE
Tài liệu thiết kế CSDL và Tài liệu thiết kế Phần mềm

### ISSUE THREAD

**Issue by trahongquan** [trahongquan/BT-TT_Team-77CH-QLTTBCNTT#6]
Đ/c Trung:
Dựa vào Tài liệu đặc tả yêu cầu để nghiên cứu và xây dựng hoàn thiện Tài liệu thiết kế CSDL và Tài liệu thiết kế Phần mềm
Hạn hoàn thành trước ngày 20/11

**Comment by Notlikeitslove** [comment]
Đã nhận!

**Comment by trahongquan** [comment]
Chỉnh sửa lại tài liệu thiết kế

**Comment by trahongquan** [comment]
OKe done
